/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiNewsletterRouteImport } from './routes/api/newsletter'
import { Route as UploadsSplatRouteImport } from './routes/uploads/$'
import { Route as ApiAdminAnnouncementsRouteImport } from './routes/api/admin/announcements'
import { Route as ApiAdminBroadcastRouteImport } from './routes/api/admin/broadcast'
import { Route as ApiAdminEventsRouteImport } from './routes/api/admin/events'
import { Route as ApiAdminGiveawaysRouteImport } from './routes/api/admin/giveaways'
import { Route as ApiAdminOverviewRouteImport } from './routes/api/admin/overview'
import { Route as ApiAdminPaymentsRouteImport } from './routes/api/admin/payments'
import { Route as ApiAdminPollsRouteImport } from './routes/api/admin/polls'
import { Route as ApiAiBookComparisonRouteImport } from './routes/api/ai/book-comparison'
import { Route as ApiAiBookSummaryRouteImport } from './routes/api/ai/book-summary'
import { Route as ApiAiDiscussRouteImport } from './routes/api/ai/discuss'
import { Route as ApiAiDiscussionQuestionsRouteImport } from './routes/api/ai/discussion-questions'
import { Route as ApiAiEventThemeRouteImport } from './routes/api/ai/event-theme'
import { Route as ApiAiReviewAssistRouteImport } from './routes/api/ai/review-assist'
import { Route as ApiAnnouncementsActiveRouteImport } from './routes/api/announcements/active'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth/reset-password'
import { Route as ApiAuthVerifyEmailRouteImport } from './routes/api/auth/verify-email'
import { Route as ApiBooksBookIdRouteImport } from './routes/api/books/$bookId'
import { Route as ApiBooksSearchRouteImport } from './routes/api/books/search'
import { Route as ApiClubBooksCurrentRouteImport } from './routes/api/club-books/current'
import { Route as ApiClubBooksHistoryRouteImport } from './routes/api/club-books/history'
import { Route as ApiDiscussionsIndexRouteImport } from './routes/api/discussions/index'
import { Route as ApiEventsIndexRouteImport } from './routes/api/events/index'
import { Route as ApiEventsEventIdRouteImport } from './routes/api/events/$eventId'
import { Route as ApiEventsUpcomingRouteImport } from './routes/api/events/upcoming'
import { Route as ApiGiveawaysIndexRouteImport } from './routes/api/giveaways/index'
import { Route as ApiLeaderboardIndexRouteImport } from './routes/api/leaderboard/index'
import { Route as ApiMeProfileRouteImport } from './routes/api/me/profile'
import { Route as ApiMembersMemberIdRouteImport } from './routes/api/members/$memberId'
import { Route as ApiPaymentsIndexRouteImport } from './routes/api/payments/index'
import { Route as ApiPaymentsCheckoutRouteImport } from './routes/api/payments/checkout'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'
import { Route as ApiPollsPollIdRouteImport } from './routes/api/polls/$pollId'
import { Route as ApiPollsActiveRouteImport } from './routes/api/polls/active'
import { Route as ApiReviewsReviewIdRouteImport } from './routes/api/reviews/$reviewId'
import { Route as ApiSuggestionsIndexRouteImport } from './routes/api/suggestions/index'
import { Route as ApiWidgetHomeRouteImport } from './routes/api/widget/home'
import { Route as ApiAdminBooksImportRouteImport } from './routes/api/admin/books/import'
import { Route as ApiAdminClubBooksCurrentRouteImport } from './routes/api/admin/club-books/current'
import { Route as ApiAdminEventsEventIdRouteImport } from './routes/api/admin/events/$eventId'
import { Route as ApiAdminMembersMemberIdRouteImport } from './routes/api/admin/members/$memberId'
import { Route as ApiAdminReviewsReviewIdRouteImport } from './routes/api/admin/reviews/$reviewId'
import { Route as ApiAdminSuggestionsSuggestionIdRouteImport } from './routes/api/admin/suggestions/$suggestionId'
import { Route as ApiBooksBookIdRatingRouteImport } from './routes/api/books/$bookId/rating'
import { Route as ApiBooksBookIdReviewsRouteImport } from './routes/api/books/$bookId/reviews'
import { Route as ApiDiscussionsThreadIdCommentsRouteImport } from './routes/api/discussions/$threadId/comments'
import { Route as ApiEventsEventIdAttendeesRouteImport } from './routes/api/events/$eventId/attendees'
import { Route as ApiEventsEventIdRsvpRouteImport } from './routes/api/events/$eventId/rsvp'
import { Route as ApiGalleryEventsEventIdRouteImport } from './routes/api/gallery/events/$eventId'
import { Route as ApiGalleryPhotosPhotoIdRouteImport } from './routes/api/gallery/photos/$photoId'
import { Route as ApiGiveawaysGiveawayIdEnterRouteImport } from './routes/api/giveaways/$giveawayId/enter'
import { Route as ApiPollsPollIdResultsRouteImport } from './routes/api/polls/$pollId/results'
import { Route as ApiPollsPollIdVoteRouteImport } from './routes/api/polls/$pollId/vote'

const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterRoute = ApiNewsletterRouteImport.update({
  id: '/api/newsletter',
  path: '/api/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAnnouncementsRoute = ApiAdminAnnouncementsRouteImport.update({
  id: '/api/admin/announcements',
  path: '/api/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBroadcastRoute = ApiAdminBroadcastRouteImport.update({
  id: '/api/admin/broadcast',
  path: '/api/admin/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEventsRoute = ApiAdminEventsRouteImport.update({
  id: '/api/admin/events',
  path: '/api/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGiveawaysRoute = ApiAdminGiveawaysRouteImport.update({
  id: '/api/admin/giveaways',
  path: '/api/admin/giveaways',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOverviewRoute = ApiAdminOverviewRouteImport.update({
  id: '/api/admin/overview',
  path: '/api/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymentsRoute = ApiAdminPaymentsRouteImport.update({
  id: '/api/admin/payments',
  path: '/api/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPollsRoute = ApiAdminPollsRouteImport.update({
  id: '/api/admin/polls',
  path: '/api/admin/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiBookComparisonRoute = ApiAiBookComparisonRouteImport.update({
  id: '/api/ai/book-comparison',
  path: '/api/ai/book-comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiBookSummaryRoute = ApiAiBookSummaryRouteImport.update({
  id: '/api/ai/book-summary',
  path: '/api/ai/book-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiDiscussRoute = ApiAiDiscussRouteImport.update({
  id: '/api/ai/discuss',
  path: '/api/ai/discuss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiDiscussionQuestionsRoute =
  ApiAiDiscussionQuestionsRouteImport.update({
    id: '/api/ai/discussion-questions',
    path: '/api/ai/discussion-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiEventThemeRoute = ApiAiEventThemeRouteImport.update({
  id: '/api/ai/event-theme',
  path: '/api/ai/event-theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiReviewAssistRoute = ApiAiReviewAssistRouteImport.update({
  id: '/api/ai/review-assist',
  path: '/api/ai/review-assist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnnouncementsActiveRoute = ApiAnnouncementsActiveRouteImport.update({
  id: '/api/announcements/active',
  path: '/api/announcements/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyEmailRoute = ApiAuthVerifyEmailRouteImport.update({
  id: '/api/auth/verify-email',
  path: '/api/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksBookIdRoute = ApiBooksBookIdRouteImport.update({
  id: '/api/books/$bookId',
  path: '/api/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksSearchRoute = ApiBooksSearchRouteImport.update({
  id: '/api/books/search',
  path: '/api/books/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClubBooksCurrentRoute = ApiClubBooksCurrentRouteImport.update({
  id: '/api/club-books/current',
  path: '/api/club-books/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClubBooksHistoryRoute = ApiClubBooksHistoryRouteImport.update({
  id: '/api/club-books/history',
  path: '/api/club-books/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscussionsIndexRoute = ApiDiscussionsIndexRouteImport.update({
  id: '/api/discussions/',
  path: '/api/discussions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIndexRoute = ApiEventsIndexRouteImport.update({
  id: '/api/events/',
  path: '/api/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsEventIdRoute = ApiEventsEventIdRouteImport.update({
  id: '/api/events/$eventId',
  path: '/api/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsUpcomingRoute = ApiEventsUpcomingRouteImport.update({
  id: '/api/events/upcoming',
  path: '/api/events/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGiveawaysIndexRoute = ApiGiveawaysIndexRouteImport.update({
  id: '/api/giveaways/',
  path: '/api/giveaways/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardIndexRoute = ApiLeaderboardIndexRouteImport.update({
  id: '/api/leaderboard/',
  path: '/api/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeProfileRoute = ApiMeProfileRouteImport.update({
  id: '/api/me/profile',
  path: '/api/me/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMembersMemberIdRoute = ApiMembersMemberIdRouteImport.update({
  id: '/api/members/$memberId',
  path: '/api/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsIndexRoute = ApiPaymentsIndexRouteImport.update({
  id: '/api/payments/',
  path: '/api/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCheckoutRoute = ApiPaymentsCheckoutRouteImport.update({
  id: '/api/payments/checkout',
  path: '/api/payments/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPollsPollIdRoute = ApiPollsPollIdRouteImport.update({
  id: '/api/polls/$pollId',
  path: '/api/polls/$pollId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPollsActiveRoute = ApiPollsActiveRouteImport.update({
  id: '/api/polls/active',
  path: '/api/polls/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsReviewIdRoute = ApiReviewsReviewIdRouteImport.update({
  id: '/api/reviews/$reviewId',
  path: '/api/reviews/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestionsIndexRoute = ApiSuggestionsIndexRouteImport.update({
  id: '/api/suggestions/',
  path: '/api/suggestions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetHomeRoute = ApiWidgetHomeRouteImport.update({
  id: '/api/widget/home',
  path: '/api/widget/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBooksImportRoute = ApiAdminBooksImportRouteImport.update({
  id: '/api/admin/books/import',
  path: '/api/admin/books/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminClubBooksCurrentRoute =
  ApiAdminClubBooksCurrentRouteImport.update({
    id: '/api/admin/club-books/current',
    path: '/api/admin/club-books/current',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminEventsEventIdRoute = ApiAdminEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => ApiAdminEventsRoute,
} as any)
const ApiAdminMembersMemberIdRoute = ApiAdminMembersMemberIdRouteImport.update({
  id: '/api/admin/members/$memberId',
  path: '/api/admin/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReviewsReviewIdRoute = ApiAdminReviewsReviewIdRouteImport.update({
  id: '/api/admin/reviews/$reviewId',
  path: '/api/admin/reviews/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSuggestionsSuggestionIdRoute =
  ApiAdminSuggestionsSuggestionIdRouteImport.update({
    id: '/api/admin/suggestions/$suggestionId',
    path: '/api/admin/suggestions/$suggestionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBooksBookIdRatingRoute = ApiBooksBookIdRatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => ApiBooksBookIdRoute,
} as any)
const ApiBooksBookIdReviewsRoute = ApiBooksBookIdReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ApiBooksBookIdRoute,
} as any)
const ApiDiscussionsThreadIdCommentsRoute =
  ApiDiscussionsThreadIdCommentsRouteImport.update({
    id: '/api/discussions/$threadId/comments',
    path: '/api/discussions/$threadId/comments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEventsEventIdAttendeesRoute =
  ApiEventsEventIdAttendeesRouteImport.update({
    id: '/attendees',
    path: '/attendees',
    getParentRoute: () => ApiEventsEventIdRoute,
  } as any)
const ApiEventsEventIdRsvpRoute = ApiEventsEventIdRsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => ApiEventsEventIdRoute,
} as any)
const ApiGalleryEventsEventIdRoute = ApiGalleryEventsEventIdRouteImport.update({
  id: '/api/gallery/events/$eventId',
  path: '/api/gallery/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGalleryPhotosPhotoIdRoute = ApiGalleryPhotosPhotoIdRouteImport.update({
  id: '/api/gallery/photos/$photoId',
  path: '/api/gallery/photos/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGiveawaysGiveawayIdEnterRoute =
  ApiGiveawaysGiveawayIdEnterRouteImport.update({
    id: '/api/giveaways/$giveawayId/enter',
    path: '/api/giveaways/$giveawayId/enter',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPollsPollIdResultsRoute = ApiPollsPollIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ApiPollsPollIdRoute,
} as any)
const ApiPollsPollIdVoteRoute = ApiPollsPollIdVoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => ApiPollsPollIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/api/health': typeof ApiHealthRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/api/admin/announcements': typeof ApiAdminAnnouncementsRoute
  '/api/admin/broadcast': typeof ApiAdminBroadcastRoute
  '/api/admin/events': typeof ApiAdminEventsRouteWithChildren
  '/api/admin/giveaways': typeof ApiAdminGiveawaysRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/payments': typeof ApiAdminPaymentsRoute
  '/api/admin/polls': typeof ApiAdminPollsRoute
  '/api/ai/book-comparison': typeof ApiAiBookComparisonRoute
  '/api/ai/book-summary': typeof ApiAiBookSummaryRoute
  '/api/ai/discuss': typeof ApiAiDiscussRoute
  '/api/ai/discussion-questions': typeof ApiAiDiscussionQuestionsRoute
  '/api/ai/event-theme': typeof ApiAiEventThemeRoute
  '/api/ai/review-assist': typeof ApiAiReviewAssistRoute
  '/api/announcements/active': typeof ApiAnnouncementsActiveRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/books/$bookId': typeof ApiBooksBookIdRouteWithChildren
  '/api/books/search': typeof ApiBooksSearchRoute
  '/api/club-books/current': typeof ApiClubBooksCurrentRoute
  '/api/club-books/history': typeof ApiClubBooksHistoryRoute
  '/api/events/$eventId': typeof ApiEventsEventIdRouteWithChildren
  '/api/events/upcoming': typeof ApiEventsUpcomingRoute
  '/api/me/profile': typeof ApiMeProfileRoute
  '/api/members/$memberId': typeof ApiMembersMemberIdRoute
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/polls/$pollId': typeof ApiPollsPollIdRouteWithChildren
  '/api/polls/active': typeof ApiPollsActiveRoute
  '/api/reviews/$reviewId': typeof ApiReviewsReviewIdRoute
  '/api/widget/home': typeof ApiWidgetHomeRoute
  '/api/discussions/': typeof ApiDiscussionsIndexRoute
  '/api/events/': typeof ApiEventsIndexRoute
  '/api/giveaways/': typeof ApiGiveawaysIndexRoute
  '/api/leaderboard/': typeof ApiLeaderboardIndexRoute
  '/api/payments/': typeof ApiPaymentsIndexRoute
  '/api/suggestions/': typeof ApiSuggestionsIndexRoute
  '/api/admin/books/import': typeof ApiAdminBooksImportRoute
  '/api/admin/club-books/current': typeof ApiAdminClubBooksCurrentRoute
  '/api/admin/events/$eventId': typeof ApiAdminEventsEventIdRoute
  '/api/admin/members/$memberId': typeof ApiAdminMembersMemberIdRoute
  '/api/admin/reviews/$reviewId': typeof ApiAdminReviewsReviewIdRoute
  '/api/admin/suggestions/$suggestionId': typeof ApiAdminSuggestionsSuggestionIdRoute
  '/api/books/$bookId/rating': typeof ApiBooksBookIdRatingRoute
  '/api/books/$bookId/reviews': typeof ApiBooksBookIdReviewsRoute
  '/api/discussions/$threadId/comments': typeof ApiDiscussionsThreadIdCommentsRoute
  '/api/events/$eventId/attendees': typeof ApiEventsEventIdAttendeesRoute
  '/api/events/$eventId/rsvp': typeof ApiEventsEventIdRsvpRoute
  '/api/gallery/events/$eventId': typeof ApiGalleryEventsEventIdRoute
  '/api/gallery/photos/$photoId': typeof ApiGalleryPhotosPhotoIdRoute
  '/api/giveaways/$giveawayId/enter': typeof ApiGiveawaysGiveawayIdEnterRoute
  '/api/polls/$pollId/results': typeof ApiPollsPollIdResultsRoute
  '/api/polls/$pollId/vote': typeof ApiPollsPollIdVoteRoute
}
export interface FileRoutesByTo {
  '/api/health': typeof ApiHealthRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/api/admin/announcements': typeof ApiAdminAnnouncementsRoute
  '/api/admin/broadcast': typeof ApiAdminBroadcastRoute
  '/api/admin/events': typeof ApiAdminEventsRouteWithChildren
  '/api/admin/giveaways': typeof ApiAdminGiveawaysRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/payments': typeof ApiAdminPaymentsRoute
  '/api/admin/polls': typeof ApiAdminPollsRoute
  '/api/ai/book-comparison': typeof ApiAiBookComparisonRoute
  '/api/ai/book-summary': typeof ApiAiBookSummaryRoute
  '/api/ai/discuss': typeof ApiAiDiscussRoute
  '/api/ai/discussion-questions': typeof ApiAiDiscussionQuestionsRoute
  '/api/ai/event-theme': typeof ApiAiEventThemeRoute
  '/api/ai/review-assist': typeof ApiAiReviewAssistRoute
  '/api/announcements/active': typeof ApiAnnouncementsActiveRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/books/$bookId': typeof ApiBooksBookIdRouteWithChildren
  '/api/books/search': typeof ApiBooksSearchRoute
  '/api/club-books/current': typeof ApiClubBooksCurrentRoute
  '/api/club-books/history': typeof ApiClubBooksHistoryRoute
  '/api/events/$eventId': typeof ApiEventsEventIdRouteWithChildren
  '/api/events/upcoming': typeof ApiEventsUpcomingRoute
  '/api/me/profile': typeof ApiMeProfileRoute
  '/api/members/$memberId': typeof ApiMembersMemberIdRoute
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/polls/$pollId': typeof ApiPollsPollIdRouteWithChildren
  '/api/polls/active': typeof ApiPollsActiveRoute
  '/api/reviews/$reviewId': typeof ApiReviewsReviewIdRoute
  '/api/widget/home': typeof ApiWidgetHomeRoute
  '/api/discussions': typeof ApiDiscussionsIndexRoute
  '/api/events': typeof ApiEventsIndexRoute
  '/api/giveaways': typeof ApiGiveawaysIndexRoute
  '/api/leaderboard': typeof ApiLeaderboardIndexRoute
  '/api/payments': typeof ApiPaymentsIndexRoute
  '/api/suggestions': typeof ApiSuggestionsIndexRoute
  '/api/admin/books/import': typeof ApiAdminBooksImportRoute
  '/api/admin/club-books/current': typeof ApiAdminClubBooksCurrentRoute
  '/api/admin/events/$eventId': typeof ApiAdminEventsEventIdRoute
  '/api/admin/members/$memberId': typeof ApiAdminMembersMemberIdRoute
  '/api/admin/reviews/$reviewId': typeof ApiAdminReviewsReviewIdRoute
  '/api/admin/suggestions/$suggestionId': typeof ApiAdminSuggestionsSuggestionIdRoute
  '/api/books/$bookId/rating': typeof ApiBooksBookIdRatingRoute
  '/api/books/$bookId/reviews': typeof ApiBooksBookIdReviewsRoute
  '/api/discussions/$threadId/comments': typeof ApiDiscussionsThreadIdCommentsRoute
  '/api/events/$eventId/attendees': typeof ApiEventsEventIdAttendeesRoute
  '/api/events/$eventId/rsvp': typeof ApiEventsEventIdRsvpRoute
  '/api/gallery/events/$eventId': typeof ApiGalleryEventsEventIdRoute
  '/api/gallery/photos/$photoId': typeof ApiGalleryPhotosPhotoIdRoute
  '/api/giveaways/$giveawayId/enter': typeof ApiGiveawaysGiveawayIdEnterRoute
  '/api/polls/$pollId/results': typeof ApiPollsPollIdResultsRoute
  '/api/polls/$pollId/vote': typeof ApiPollsPollIdVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/health': typeof ApiHealthRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/api/admin/announcements': typeof ApiAdminAnnouncementsRoute
  '/api/admin/broadcast': typeof ApiAdminBroadcastRoute
  '/api/admin/events': typeof ApiAdminEventsRouteWithChildren
  '/api/admin/giveaways': typeof ApiAdminGiveawaysRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/payments': typeof ApiAdminPaymentsRoute
  '/api/admin/polls': typeof ApiAdminPollsRoute
  '/api/ai/book-comparison': typeof ApiAiBookComparisonRoute
  '/api/ai/book-summary': typeof ApiAiBookSummaryRoute
  '/api/ai/discuss': typeof ApiAiDiscussRoute
  '/api/ai/discussion-questions': typeof ApiAiDiscussionQuestionsRoute
  '/api/ai/event-theme': typeof ApiAiEventThemeRoute
  '/api/ai/review-assist': typeof ApiAiReviewAssistRoute
  '/api/announcements/active': typeof ApiAnnouncementsActiveRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/books/$bookId': typeof ApiBooksBookIdRouteWithChildren
  '/api/books/search': typeof ApiBooksSearchRoute
  '/api/club-books/current': typeof ApiClubBooksCurrentRoute
  '/api/club-books/history': typeof ApiClubBooksHistoryRoute
  '/api/events/$eventId': typeof ApiEventsEventIdRouteWithChildren
  '/api/events/upcoming': typeof ApiEventsUpcomingRoute
  '/api/me/profile': typeof ApiMeProfileRoute
  '/api/members/$memberId': typeof ApiMembersMemberIdRoute
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/polls/$pollId': typeof ApiPollsPollIdRouteWithChildren
  '/api/polls/active': typeof ApiPollsActiveRoute
  '/api/reviews/$reviewId': typeof ApiReviewsReviewIdRoute
  '/api/widget/home': typeof ApiWidgetHomeRoute
  '/api/discussions/': typeof ApiDiscussionsIndexRoute
  '/api/events/': typeof ApiEventsIndexRoute
  '/api/giveaways/': typeof ApiGiveawaysIndexRoute
  '/api/leaderboard/': typeof ApiLeaderboardIndexRoute
  '/api/payments/': typeof ApiPaymentsIndexRoute
  '/api/suggestions/': typeof ApiSuggestionsIndexRoute
  '/api/admin/books/import': typeof ApiAdminBooksImportRoute
  '/api/admin/club-books/current': typeof ApiAdminClubBooksCurrentRoute
  '/api/admin/events/$eventId': typeof ApiAdminEventsEventIdRoute
  '/api/admin/members/$memberId': typeof ApiAdminMembersMemberIdRoute
  '/api/admin/reviews/$reviewId': typeof ApiAdminReviewsReviewIdRoute
  '/api/admin/suggestions/$suggestionId': typeof ApiAdminSuggestionsSuggestionIdRoute
  '/api/books/$bookId/rating': typeof ApiBooksBookIdRatingRoute
  '/api/books/$bookId/reviews': typeof ApiBooksBookIdReviewsRoute
  '/api/discussions/$threadId/comments': typeof ApiDiscussionsThreadIdCommentsRoute
  '/api/events/$eventId/attendees': typeof ApiEventsEventIdAttendeesRoute
  '/api/events/$eventId/rsvp': typeof ApiEventsEventIdRsvpRoute
  '/api/gallery/events/$eventId': typeof ApiGalleryEventsEventIdRoute
  '/api/gallery/photos/$photoId': typeof ApiGalleryPhotosPhotoIdRoute
  '/api/giveaways/$giveawayId/enter': typeof ApiGiveawaysGiveawayIdEnterRoute
  '/api/polls/$pollId/results': typeof ApiPollsPollIdResultsRoute
  '/api/polls/$pollId/vote': typeof ApiPollsPollIdVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/health'
    | '/api/newsletter'
    | '/uploads/$'
    | '/api/admin/announcements'
    | '/api/admin/broadcast'
    | '/api/admin/events'
    | '/api/admin/giveaways'
    | '/api/admin/overview'
    | '/api/admin/payments'
    | '/api/admin/polls'
    | '/api/ai/book-comparison'
    | '/api/ai/book-summary'
    | '/api/ai/discuss'
    | '/api/ai/discussion-questions'
    | '/api/ai/event-theme'
    | '/api/ai/review-assist'
    | '/api/announcements/active'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/refresh'
    | '/api/auth/register'
    | '/api/auth/reset-password'
    | '/api/auth/verify-email'
    | '/api/books/$bookId'
    | '/api/books/search'
    | '/api/club-books/current'
    | '/api/club-books/history'
    | '/api/events/$eventId'
    | '/api/events/upcoming'
    | '/api/me/profile'
    | '/api/members/$memberId'
    | '/api/payments/checkout'
    | '/api/payments/webhook'
    | '/api/polls/$pollId'
    | '/api/polls/active'
    | '/api/reviews/$reviewId'
    | '/api/widget/home'
    | '/api/discussions/'
    | '/api/events/'
    | '/api/giveaways/'
    | '/api/leaderboard/'
    | '/api/payments/'
    | '/api/suggestions/'
    | '/api/admin/books/import'
    | '/api/admin/club-books/current'
    | '/api/admin/events/$eventId'
    | '/api/admin/members/$memberId'
    | '/api/admin/reviews/$reviewId'
    | '/api/admin/suggestions/$suggestionId'
    | '/api/books/$bookId/rating'
    | '/api/books/$bookId/reviews'
    | '/api/discussions/$threadId/comments'
    | '/api/events/$eventId/attendees'
    | '/api/events/$eventId/rsvp'
    | '/api/gallery/events/$eventId'
    | '/api/gallery/photos/$photoId'
    | '/api/giveaways/$giveawayId/enter'
    | '/api/polls/$pollId/results'
    | '/api/polls/$pollId/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/health'
    | '/api/newsletter'
    | '/uploads/$'
    | '/api/admin/announcements'
    | '/api/admin/broadcast'
    | '/api/admin/events'
    | '/api/admin/giveaways'
    | '/api/admin/overview'
    | '/api/admin/payments'
    | '/api/admin/polls'
    | '/api/ai/book-comparison'
    | '/api/ai/book-summary'
    | '/api/ai/discuss'
    | '/api/ai/discussion-questions'
    | '/api/ai/event-theme'
    | '/api/ai/review-assist'
    | '/api/announcements/active'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/refresh'
    | '/api/auth/register'
    | '/api/auth/reset-password'
    | '/api/auth/verify-email'
    | '/api/books/$bookId'
    | '/api/books/search'
    | '/api/club-books/current'
    | '/api/club-books/history'
    | '/api/events/$eventId'
    | '/api/events/upcoming'
    | '/api/me/profile'
    | '/api/members/$memberId'
    | '/api/payments/checkout'
    | '/api/payments/webhook'
    | '/api/polls/$pollId'
    | '/api/polls/active'
    | '/api/reviews/$reviewId'
    | '/api/widget/home'
    | '/api/discussions'
    | '/api/events'
    | '/api/giveaways'
    | '/api/leaderboard'
    | '/api/payments'
    | '/api/suggestions'
    | '/api/admin/books/import'
    | '/api/admin/club-books/current'
    | '/api/admin/events/$eventId'
    | '/api/admin/members/$memberId'
    | '/api/admin/reviews/$reviewId'
    | '/api/admin/suggestions/$suggestionId'
    | '/api/books/$bookId/rating'
    | '/api/books/$bookId/reviews'
    | '/api/discussions/$threadId/comments'
    | '/api/events/$eventId/attendees'
    | '/api/events/$eventId/rsvp'
    | '/api/gallery/events/$eventId'
    | '/api/gallery/photos/$photoId'
    | '/api/giveaways/$giveawayId/enter'
    | '/api/polls/$pollId/results'
    | '/api/polls/$pollId/vote'
  id:
    | '__root__'
    | '/api/health'
    | '/api/newsletter'
    | '/uploads/$'
    | '/api/admin/announcements'
    | '/api/admin/broadcast'
    | '/api/admin/events'
    | '/api/admin/giveaways'
    | '/api/admin/overview'
    | '/api/admin/payments'
    | '/api/admin/polls'
    | '/api/ai/book-comparison'
    | '/api/ai/book-summary'
    | '/api/ai/discuss'
    | '/api/ai/discussion-questions'
    | '/api/ai/event-theme'
    | '/api/ai/review-assist'
    | '/api/announcements/active'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/refresh'
    | '/api/auth/register'
    | '/api/auth/reset-password'
    | '/api/auth/verify-email'
    | '/api/books/$bookId'
    | '/api/books/search'
    | '/api/club-books/current'
    | '/api/club-books/history'
    | '/api/events/$eventId'
    | '/api/events/upcoming'
    | '/api/me/profile'
    | '/api/members/$memberId'
    | '/api/payments/checkout'
    | '/api/payments/webhook'
    | '/api/polls/$pollId'
    | '/api/polls/active'
    | '/api/reviews/$reviewId'
    | '/api/widget/home'
    | '/api/discussions/'
    | '/api/events/'
    | '/api/giveaways/'
    | '/api/leaderboard/'
    | '/api/payments/'
    | '/api/suggestions/'
    | '/api/admin/books/import'
    | '/api/admin/club-books/current'
    | '/api/admin/events/$eventId'
    | '/api/admin/members/$memberId'
    | '/api/admin/reviews/$reviewId'
    | '/api/admin/suggestions/$suggestionId'
    | '/api/books/$bookId/rating'
    | '/api/books/$bookId/reviews'
    | '/api/discussions/$threadId/comments'
    | '/api/events/$eventId/attendees'
    | '/api/events/$eventId/rsvp'
    | '/api/gallery/events/$eventId'
    | '/api/gallery/photos/$photoId'
    | '/api/giveaways/$giveawayId/enter'
    | '/api/polls/$pollId/results'
    | '/api/polls/$pollId/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNewsletterRoute: typeof ApiNewsletterRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  ApiAdminAnnouncementsRoute: typeof ApiAdminAnnouncementsRoute
  ApiAdminBroadcastRoute: typeof ApiAdminBroadcastRoute
  ApiAdminEventsRoute: typeof ApiAdminEventsRouteWithChildren
  ApiAdminGiveawaysRoute: typeof ApiAdminGiveawaysRoute
  ApiAdminOverviewRoute: typeof ApiAdminOverviewRoute
  ApiAdminPaymentsRoute: typeof ApiAdminPaymentsRoute
  ApiAdminPollsRoute: typeof ApiAdminPollsRoute
  ApiAiBookComparisonRoute: typeof ApiAiBookComparisonRoute
  ApiAiBookSummaryRoute: typeof ApiAiBookSummaryRoute
  ApiAiDiscussRoute: typeof ApiAiDiscussRoute
  ApiAiDiscussionQuestionsRoute: typeof ApiAiDiscussionQuestionsRoute
  ApiAiEventThemeRoute: typeof ApiAiEventThemeRoute
  ApiAiReviewAssistRoute: typeof ApiAiReviewAssistRoute
  ApiAnnouncementsActiveRoute: typeof ApiAnnouncementsActiveRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiAuthVerifyEmailRoute: typeof ApiAuthVerifyEmailRoute
  ApiBooksBookIdRoute: typeof ApiBooksBookIdRouteWithChildren
  ApiBooksSearchRoute: typeof ApiBooksSearchRoute
  ApiClubBooksCurrentRoute: typeof ApiClubBooksCurrentRoute
  ApiClubBooksHistoryRoute: typeof ApiClubBooksHistoryRoute
  ApiEventsEventIdRoute: typeof ApiEventsEventIdRouteWithChildren
  ApiEventsUpcomingRoute: typeof ApiEventsUpcomingRoute
  ApiMeProfileRoute: typeof ApiMeProfileRoute
  ApiMembersMemberIdRoute: typeof ApiMembersMemberIdRoute
  ApiPaymentsCheckoutRoute: typeof ApiPaymentsCheckoutRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
  ApiPollsPollIdRoute: typeof ApiPollsPollIdRouteWithChildren
  ApiPollsActiveRoute: typeof ApiPollsActiveRoute
  ApiReviewsReviewIdRoute: typeof ApiReviewsReviewIdRoute
  ApiWidgetHomeRoute: typeof ApiWidgetHomeRoute
  ApiDiscussionsIndexRoute: typeof ApiDiscussionsIndexRoute
  ApiEventsIndexRoute: typeof ApiEventsIndexRoute
  ApiGiveawaysIndexRoute: typeof ApiGiveawaysIndexRoute
  ApiLeaderboardIndexRoute: typeof ApiLeaderboardIndexRoute
  ApiPaymentsIndexRoute: typeof ApiPaymentsIndexRoute
  ApiSuggestionsIndexRoute: typeof ApiSuggestionsIndexRoute
  ApiAdminBooksImportRoute: typeof ApiAdminBooksImportRoute
  ApiAdminClubBooksCurrentRoute: typeof ApiAdminClubBooksCurrentRoute
  ApiAdminMembersMemberIdRoute: typeof ApiAdminMembersMemberIdRoute
  ApiAdminReviewsReviewIdRoute: typeof ApiAdminReviewsReviewIdRoute
  ApiAdminSuggestionsSuggestionIdRoute: typeof ApiAdminSuggestionsSuggestionIdRoute
  ApiDiscussionsThreadIdCommentsRoute: typeof ApiDiscussionsThreadIdCommentsRoute
  ApiGalleryEventsEventIdRoute: typeof ApiGalleryEventsEventIdRoute
  ApiGalleryPhotosPhotoIdRoute: typeof ApiGalleryPhotosPhotoIdRoute
  ApiGiveawaysGiveawayIdEnterRoute: typeof ApiGiveawaysGiveawayIdEnterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter': {
      id: '/api/newsletter'
      path: '/api/newsletter'
      fullPath: '/api/newsletter'
      preLoaderRoute: typeof ApiNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/announcements': {
      id: '/api/admin/announcements'
      path: '/api/admin/announcements'
      fullPath: '/api/admin/announcements'
      preLoaderRoute: typeof ApiAdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/broadcast': {
      id: '/api/admin/broadcast'
      path: '/api/admin/broadcast'
      fullPath: '/api/admin/broadcast'
      preLoaderRoute: typeof ApiAdminBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/events': {
      id: '/api/admin/events'
      path: '/api/admin/events'
      fullPath: '/api/admin/events'
      preLoaderRoute: typeof ApiAdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/giveaways': {
      id: '/api/admin/giveaways'
      path: '/api/admin/giveaways'
      fullPath: '/api/admin/giveaways'
      preLoaderRoute: typeof ApiAdminGiveawaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/overview': {
      id: '/api/admin/overview'
      path: '/api/admin/overview'
      fullPath: '/api/admin/overview'
      preLoaderRoute: typeof ApiAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payments': {
      id: '/api/admin/payments'
      path: '/api/admin/payments'
      fullPath: '/api/admin/payments'
      preLoaderRoute: typeof ApiAdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/polls': {
      id: '/api/admin/polls'
      path: '/api/admin/polls'
      fullPath: '/api/admin/polls'
      preLoaderRoute: typeof ApiAdminPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/book-comparison': {
      id: '/api/ai/book-comparison'
      path: '/api/ai/book-comparison'
      fullPath: '/api/ai/book-comparison'
      preLoaderRoute: typeof ApiAiBookComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/book-summary': {
      id: '/api/ai/book-summary'
      path: '/api/ai/book-summary'
      fullPath: '/api/ai/book-summary'
      preLoaderRoute: typeof ApiAiBookSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/discuss': {
      id: '/api/ai/discuss'
      path: '/api/ai/discuss'
      fullPath: '/api/ai/discuss'
      preLoaderRoute: typeof ApiAiDiscussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/discussion-questions': {
      id: '/api/ai/discussion-questions'
      path: '/api/ai/discussion-questions'
      fullPath: '/api/ai/discussion-questions'
      preLoaderRoute: typeof ApiAiDiscussionQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/event-theme': {
      id: '/api/ai/event-theme'
      path: '/api/ai/event-theme'
      fullPath: '/api/ai/event-theme'
      preLoaderRoute: typeof ApiAiEventThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/review-assist': {
      id: '/api/ai/review-assist'
      path: '/api/ai/review-assist'
      fullPath: '/api/ai/review-assist'
      preLoaderRoute: typeof ApiAiReviewAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/announcements/active': {
      id: '/api/announcements/active'
      path: '/api/announcements/active'
      fullPath: '/api/announcements/active'
      preLoaderRoute: typeof ApiAnnouncementsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-email': {
      id: '/api/auth/verify-email'
      path: '/api/auth/verify-email'
      fullPath: '/api/auth/verify-email'
      preLoaderRoute: typeof ApiAuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/$bookId': {
      id: '/api/books/$bookId'
      path: '/api/books/$bookId'
      fullPath: '/api/books/$bookId'
      preLoaderRoute: typeof ApiBooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/search': {
      id: '/api/books/search'
      path: '/api/books/search'
      fullPath: '/api/books/search'
      preLoaderRoute: typeof ApiBooksSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/club-books/current': {
      id: '/api/club-books/current'
      path: '/api/club-books/current'
      fullPath: '/api/club-books/current'
      preLoaderRoute: typeof ApiClubBooksCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/club-books/history': {
      id: '/api/club-books/history'
      path: '/api/club-books/history'
      fullPath: '/api/club-books/history'
      preLoaderRoute: typeof ApiClubBooksHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discussions/': {
      id: '/api/discussions/'
      path: '/api/discussions'
      fullPath: '/api/discussions/'
      preLoaderRoute: typeof ApiDiscussionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/': {
      id: '/api/events/'
      path: '/api/events'
      fullPath: '/api/events/'
      preLoaderRoute: typeof ApiEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$eventId': {
      id: '/api/events/$eventId'
      path: '/api/events/$eventId'
      fullPath: '/api/events/$eventId'
      preLoaderRoute: typeof ApiEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/upcoming': {
      id: '/api/events/upcoming'
      path: '/api/events/upcoming'
      fullPath: '/api/events/upcoming'
      preLoaderRoute: typeof ApiEventsUpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/giveaways/': {
      id: '/api/giveaways/'
      path: '/api/giveaways'
      fullPath: '/api/giveaways/'
      preLoaderRoute: typeof ApiGiveawaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard/': {
      id: '/api/leaderboard/'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard/'
      preLoaderRoute: typeof ApiLeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/profile': {
      id: '/api/me/profile'
      path: '/api/me/profile'
      fullPath: '/api/me/profile'
      preLoaderRoute: typeof ApiMeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/members/$memberId': {
      id: '/api/members/$memberId'
      path: '/api/members/$memberId'
      fullPath: '/api/members/$memberId'
      preLoaderRoute: typeof ApiMembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/': {
      id: '/api/payments/'
      path: '/api/payments'
      fullPath: '/api/payments/'
      preLoaderRoute: typeof ApiPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/checkout': {
      id: '/api/payments/checkout'
      path: '/api/payments/checkout'
      fullPath: '/api/payments/checkout'
      preLoaderRoute: typeof ApiPaymentsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polls/$pollId': {
      id: '/api/polls/$pollId'
      path: '/api/polls/$pollId'
      fullPath: '/api/polls/$pollId'
      preLoaderRoute: typeof ApiPollsPollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polls/active': {
      id: '/api/polls/active'
      path: '/api/polls/active'
      fullPath: '/api/polls/active'
      preLoaderRoute: typeof ApiPollsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/$reviewId': {
      id: '/api/reviews/$reviewId'
      path: '/api/reviews/$reviewId'
      fullPath: '/api/reviews/$reviewId'
      preLoaderRoute: typeof ApiReviewsReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggestions/': {
      id: '/api/suggestions/'
      path: '/api/suggestions'
      fullPath: '/api/suggestions/'
      preLoaderRoute: typeof ApiSuggestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widget/home': {
      id: '/api/widget/home'
      path: '/api/widget/home'
      fullPath: '/api/widget/home'
      preLoaderRoute: typeof ApiWidgetHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/books/import': {
      id: '/api/admin/books/import'
      path: '/api/admin/books/import'
      fullPath: '/api/admin/books/import'
      preLoaderRoute: typeof ApiAdminBooksImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/club-books/current': {
      id: '/api/admin/club-books/current'
      path: '/api/admin/club-books/current'
      fullPath: '/api/admin/club-books/current'
      preLoaderRoute: typeof ApiAdminClubBooksCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/events/$eventId': {
      id: '/api/admin/events/$eventId'
      path: '/$eventId'
      fullPath: '/api/admin/events/$eventId'
      preLoaderRoute: typeof ApiAdminEventsEventIdRouteImport
      parentRoute: typeof ApiAdminEventsRoute
    }
    '/api/admin/members/$memberId': {
      id: '/api/admin/members/$memberId'
      path: '/api/admin/members/$memberId'
      fullPath: '/api/admin/members/$memberId'
      preLoaderRoute: typeof ApiAdminMembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reviews/$reviewId': {
      id: '/api/admin/reviews/$reviewId'
      path: '/api/admin/reviews/$reviewId'
      fullPath: '/api/admin/reviews/$reviewId'
      preLoaderRoute: typeof ApiAdminReviewsReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/suggestions/$suggestionId': {
      id: '/api/admin/suggestions/$suggestionId'
      path: '/api/admin/suggestions/$suggestionId'
      fullPath: '/api/admin/suggestions/$suggestionId'
      preLoaderRoute: typeof ApiAdminSuggestionsSuggestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/$bookId/rating': {
      id: '/api/books/$bookId/rating'
      path: '/rating'
      fullPath: '/api/books/$bookId/rating'
      preLoaderRoute: typeof ApiBooksBookIdRatingRouteImport
      parentRoute: typeof ApiBooksBookIdRoute
    }
    '/api/books/$bookId/reviews': {
      id: '/api/books/$bookId/reviews'
      path: '/reviews'
      fullPath: '/api/books/$bookId/reviews'
      preLoaderRoute: typeof ApiBooksBookIdReviewsRouteImport
      parentRoute: typeof ApiBooksBookIdRoute
    }
    '/api/discussions/$threadId/comments': {
      id: '/api/discussions/$threadId/comments'
      path: '/api/discussions/$threadId/comments'
      fullPath: '/api/discussions/$threadId/comments'
      preLoaderRoute: typeof ApiDiscussionsThreadIdCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$eventId/attendees': {
      id: '/api/events/$eventId/attendees'
      path: '/attendees'
      fullPath: '/api/events/$eventId/attendees'
      preLoaderRoute: typeof ApiEventsEventIdAttendeesRouteImport
      parentRoute: typeof ApiEventsEventIdRoute
    }
    '/api/events/$eventId/rsvp': {
      id: '/api/events/$eventId/rsvp'
      path: '/rsvp'
      fullPath: '/api/events/$eventId/rsvp'
      preLoaderRoute: typeof ApiEventsEventIdRsvpRouteImport
      parentRoute: typeof ApiEventsEventIdRoute
    }
    '/api/gallery/events/$eventId': {
      id: '/api/gallery/events/$eventId'
      path: '/api/gallery/events/$eventId'
      fullPath: '/api/gallery/events/$eventId'
      preLoaderRoute: typeof ApiGalleryEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery/photos/$photoId': {
      id: '/api/gallery/photos/$photoId'
      path: '/api/gallery/photos/$photoId'
      fullPath: '/api/gallery/photos/$photoId'
      preLoaderRoute: typeof ApiGalleryPhotosPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/giveaways/$giveawayId/enter': {
      id: '/api/giveaways/$giveawayId/enter'
      path: '/api/giveaways/$giveawayId/enter'
      fullPath: '/api/giveaways/$giveawayId/enter'
      preLoaderRoute: typeof ApiGiveawaysGiveawayIdEnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polls/$pollId/results': {
      id: '/api/polls/$pollId/results'
      path: '/results'
      fullPath: '/api/polls/$pollId/results'
      preLoaderRoute: typeof ApiPollsPollIdResultsRouteImport
      parentRoute: typeof ApiPollsPollIdRoute
    }
    '/api/polls/$pollId/vote': {
      id: '/api/polls/$pollId/vote'
      path: '/vote'
      fullPath: '/api/polls/$pollId/vote'
      preLoaderRoute: typeof ApiPollsPollIdVoteRouteImport
      parentRoute: typeof ApiPollsPollIdRoute
    }
  }
}

interface ApiAdminEventsRouteChildren {
  ApiAdminEventsEventIdRoute: typeof ApiAdminEventsEventIdRoute
}

const ApiAdminEventsRouteChildren: ApiAdminEventsRouteChildren = {
  ApiAdminEventsEventIdRoute: ApiAdminEventsEventIdRoute,
}

const ApiAdminEventsRouteWithChildren = ApiAdminEventsRoute._addFileChildren(
  ApiAdminEventsRouteChildren,
)

interface ApiBooksBookIdRouteChildren {
  ApiBooksBookIdRatingRoute: typeof ApiBooksBookIdRatingRoute
  ApiBooksBookIdReviewsRoute: typeof ApiBooksBookIdReviewsRoute
}

const ApiBooksBookIdRouteChildren: ApiBooksBookIdRouteChildren = {
  ApiBooksBookIdRatingRoute: ApiBooksBookIdRatingRoute,
  ApiBooksBookIdReviewsRoute: ApiBooksBookIdReviewsRoute,
}

const ApiBooksBookIdRouteWithChildren = ApiBooksBookIdRoute._addFileChildren(
  ApiBooksBookIdRouteChildren,
)

interface ApiEventsEventIdRouteChildren {
  ApiEventsEventIdAttendeesRoute: typeof ApiEventsEventIdAttendeesRoute
  ApiEventsEventIdRsvpRoute: typeof ApiEventsEventIdRsvpRoute
}

const ApiEventsEventIdRouteChildren: ApiEventsEventIdRouteChildren = {
  ApiEventsEventIdAttendeesRoute: ApiEventsEventIdAttendeesRoute,
  ApiEventsEventIdRsvpRoute: ApiEventsEventIdRsvpRoute,
}

const ApiEventsEventIdRouteWithChildren =
  ApiEventsEventIdRoute._addFileChildren(ApiEventsEventIdRouteChildren)

interface ApiPollsPollIdRouteChildren {
  ApiPollsPollIdResultsRoute: typeof ApiPollsPollIdResultsRoute
  ApiPollsPollIdVoteRoute: typeof ApiPollsPollIdVoteRoute
}

const ApiPollsPollIdRouteChildren: ApiPollsPollIdRouteChildren = {
  ApiPollsPollIdResultsRoute: ApiPollsPollIdResultsRoute,
  ApiPollsPollIdVoteRoute: ApiPollsPollIdVoteRoute,
}

const ApiPollsPollIdRouteWithChildren = ApiPollsPollIdRoute._addFileChildren(
  ApiPollsPollIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ApiHealthRoute: ApiHealthRoute,
  ApiNewsletterRoute: ApiNewsletterRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  ApiAdminAnnouncementsRoute: ApiAdminAnnouncementsRoute,
  ApiAdminBroadcastRoute: ApiAdminBroadcastRoute,
  ApiAdminEventsRoute: ApiAdminEventsRouteWithChildren,
  ApiAdminGiveawaysRoute: ApiAdminGiveawaysRoute,
  ApiAdminOverviewRoute: ApiAdminOverviewRoute,
  ApiAdminPaymentsRoute: ApiAdminPaymentsRoute,
  ApiAdminPollsRoute: ApiAdminPollsRoute,
  ApiAiBookComparisonRoute: ApiAiBookComparisonRoute,
  ApiAiBookSummaryRoute: ApiAiBookSummaryRoute,
  ApiAiDiscussRoute: ApiAiDiscussRoute,
  ApiAiDiscussionQuestionsRoute: ApiAiDiscussionQuestionsRoute,
  ApiAiEventThemeRoute: ApiAiEventThemeRoute,
  ApiAiReviewAssistRoute: ApiAiReviewAssistRoute,
  ApiAnnouncementsActiveRoute: ApiAnnouncementsActiveRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiAuthVerifyEmailRoute: ApiAuthVerifyEmailRoute,
  ApiBooksBookIdRoute: ApiBooksBookIdRouteWithChildren,
  ApiBooksSearchRoute: ApiBooksSearchRoute,
  ApiClubBooksCurrentRoute: ApiClubBooksCurrentRoute,
  ApiClubBooksHistoryRoute: ApiClubBooksHistoryRoute,
  ApiEventsEventIdRoute: ApiEventsEventIdRouteWithChildren,
  ApiEventsUpcomingRoute: ApiEventsUpcomingRoute,
  ApiMeProfileRoute: ApiMeProfileRoute,
  ApiMembersMemberIdRoute: ApiMembersMemberIdRoute,
  ApiPaymentsCheckoutRoute: ApiPaymentsCheckoutRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
  ApiPollsPollIdRoute: ApiPollsPollIdRouteWithChildren,
  ApiPollsActiveRoute: ApiPollsActiveRoute,
  ApiReviewsReviewIdRoute: ApiReviewsReviewIdRoute,
  ApiWidgetHomeRoute: ApiWidgetHomeRoute,
  ApiDiscussionsIndexRoute: ApiDiscussionsIndexRoute,
  ApiEventsIndexRoute: ApiEventsIndexRoute,
  ApiGiveawaysIndexRoute: ApiGiveawaysIndexRoute,
  ApiLeaderboardIndexRoute: ApiLeaderboardIndexRoute,
  ApiPaymentsIndexRoute: ApiPaymentsIndexRoute,
  ApiSuggestionsIndexRoute: ApiSuggestionsIndexRoute,
  ApiAdminBooksImportRoute: ApiAdminBooksImportRoute,
  ApiAdminClubBooksCurrentRoute: ApiAdminClubBooksCurrentRoute,
  ApiAdminMembersMemberIdRoute: ApiAdminMembersMemberIdRoute,
  ApiAdminReviewsReviewIdRoute: ApiAdminReviewsReviewIdRoute,
  ApiAdminSuggestionsSuggestionIdRoute: ApiAdminSuggestionsSuggestionIdRoute,
  ApiDiscussionsThreadIdCommentsRoute: ApiDiscussionsThreadIdCommentsRoute,
  ApiGalleryEventsEventIdRoute: ApiGalleryEventsEventIdRoute,
  ApiGalleryPhotosPhotoIdRoute: ApiGalleryPhotosPhotoIdRoute,
  ApiGiveawaysGiveawayIdEnterRoute: ApiGiveawaysGiveawayIdEnterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
